#!/bin/sh

if [ "${SKIP_GIT_HOOKS}" ]; then
    exit 0
fi

make format
if [ $? -ne 0 ]; then
    echo "Pre-push linting failed."
    exit 1
fi

make lint
if [ $? -ne 0 ]; then
    echo "Pre-push linting failed."
    exit 1
fi

make test
if [ $? -ne 0 ]; then
    echo "Pre-push test execution failed."
    exit 1
fi

exit 0