name: docker

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.1.7
        with:
          fetch-tags: ${{ inputs.version }}
      - name: build docker image
        run: |
          echo "Building docker image ${{ inputs.version }} "
          echo "DOCKER IMAGE BUILDED"
      - name: push docker image
        run: |
          echo "Pushing docker image ${{ inputs.version }} to ${{ inputs.environment }}"
          echo "DOCKER IMAGE PUSHED"
