name: on release

on:
  release:
    types: [released]

concurrency:
  group: on-release

permissions:
  contents: write
  deployments: write
  id-token: write
  repository-projects: write

jobs:
  docker:
    name: "Building Docker Image: Prod"
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
    if: ${{ github.event.release.tag_name != '' }}
    with:
      environment: prod
      version: ${{ github.event.release.tag_name }}

  deploy-to-stage:
    name: "Deployment: Stage"
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
    needs: [docker]
    if: ${{ github.event.release.tag_name != '' }}
    with:
      environment: prod
      version: ${{ github.event.release.tag_name }}
